// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggpjccfadxvulnutbkub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncGpjY2ZhZHh2dWxudXRia3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NjM0NDYsImV4cCI6MjA4NDMzOTQ0Nn0.gPjOBZbEV18qVRkdOJbc4Qjuivlnd-mAtY5g8bU-y5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});